### ISSUE TITLE
Publishing CHANGELOG.m shows incorrect dates on the Hub

### ISSUE THREAD

**Issue by IjzerenHein** [release-notes/release-notes-cli#21]
Hey man! I've just integrated release-notes into my Firestorter project.
I decided to go for a `CHANGELOG.md` file and see how that works.
Generally, everything was pretty smooth, but I found 1 main issue though. The dates in the CHANGELOG.md file do not correspond the ones on the hub. They seem to be one day off, probably due to a timezone conversion.
https://github.com/IjzerenHein/firestorter/blob/master/CHANGELOG.md

And some additional feedback:
- Would love to see the `release-notes validate` command work for CHANGELOG.md files
- I couldn't find the documentation for adding a badge button (I thought I had seen it somewhere but couldn't find it afterwards)
- The text on the badge button is too long, I'd like to use a shorter version. Is there a list of available badge buttons?

Cheers dude!

**Comment by alrik** [comment]
Hey @IjzerenHein,
Thanks for your awesome feedback.
I'm on it. New badge icon is already in work :sparkles: : see [this commit](https://github.com/release-notes/release-notes-hub/commit/5b2d8bccf8b589ab75d4e1370fb855e86b1ea83f)
I'll also improve the accessebility of those badge icons in the hub.
I really like the idea of validating changelog.md files aswell. It seems an md file is handier and easier to work with in the daily dev biz. I'd like to bootstrap some [keep a changelog](https://keepachangelog.com) style validator as a first step forward. Would you like to contribute?

Cheers, and thanks ;)
Alrik

**Comment by alrik** [comment]
And yes, the date handling bugs :bug: . I'll fix this, soon.

**Comment by alrik** [comment]
I'll close this issue in favor of: release-notes/release-notes-hub#46
