### ISSUE TITLE
Cli tool converter for CHANGELOG.md 

### ISSUE THREAD

**Issue by alrik** [release-notes/release-notes-cli#8]
As a developer i'd like to generate `CHANGELOG.md` files from `release-notes.yml`

**Acceptance Criteria**:

* [ ] The converter is be called ChangelogConverter and is registered as 'changelog' converter
* [x] The command `release-notes convert -t changelog` converts the release-notes to CHANGELOG markdown that is written to stdout
* [x] The generated markdown follows the recommendations of [keep a changelog](http://keepachangelog.com/en/1.0.0/)
* [ ] The conversion is unit tested
* [ ] The conversion is documented in the readme

**Comment by alrik** [comment]
@IjzerenHein feel free to assign this to you if you like.

**Comment by IjzerenHein** [comment]
@alrik I'll check it out when I have some time :)
Also, how can I assign this to me, I don't have the rights for this?

**Comment by alrik** [comment]
@IjzerenHein I'll add you to a **contributors** group.

**Comment by IjzerenHein** [comment]
@alrik Awesome :)
